environment: {}
parameters: {}
packages:
  - name: ch
    environment:
      CH_API_KEY: ${CH_API_KEY}
    parameters: {}
    annotations: {}
    functions:
      - name: searchForCompany
        binary: false
        main: ''
        runtime: 'nodejs:18'
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
